### ISSUE TITLE
Multibyte characters in LLLVar fields lead to parsing failure

### ISSUE THREAD

**Issue by aleksey-korolev** [chochos/j8583#37] opened 2015-03-02 17:02 UTC
LLLVar fields have their length in bytes specified in LLL field prefix.
If field contains multibyte characters, then fields length is detected incorrectly when shifting pointer to the next field and parsing of a next field fails.

The problem is in LllvarParseInfo.parse code block starting at line 67 (in ver 1.10.2 I use):

``` java
        //This is new: if the String's length is different from the specified length in the
        //buffer, there are probably some extended characters. So we create a String from
        //the rest of the buffer, and then cut it to the specified length.
        if (_v.length() != len) {
            _v = new String(buf, pos + 3, buf.length-pos-3,
                    getCharacterEncoding()).substring(0, len);
        }
```

If multibyte chars present then _v.length() < len since len is in bytes.

**Comment by aleksey-korolev** [comment] 2015-03-03 15:29
Please make the fix available in Java 1.6 version too.
Let me know if you need help with fix of this issue.

**Comment by chochos** [comment] 2015-03-26 17:37
Have you tried setting the `characterEncoding` property of the `MessageFactory`?

**Comment by chochos** [comment] 2015-03-26 20:29
The code you point to actually tries to fix the problem you mention, but the length specified in the LLLVAR field has to be in bytes. So the problem is with the encoded length; was the message created with j8583?

**Comment by aleksey-korolev** [comment] 2015-03-28 08:04
Yes, setting characterEncoding to a single-byte encoding such as ANSI allow parsing not to fail but results in incorrect for UTF characters. Setting characterEncoding to UTF-8 leads to the described problem.
The message wasn't created with j8583 (message producer in our project is an existing external system we don't have control over) but I could create a small java test to demonstrate the issue if you'd like.

**Comment by chochos** [comment] 2015-03-30 19:18
In the meantime you can set the field to LLLBIN instead and retrieve the bytes, so you can decode them to whatever encoding you need. The root cause of the problem here is the length indicator; there are two possible values the length indicator could have: the byte count, or the character count in the expected encoding. j8583 expects the character count and it seems you're receiving the character count. I guess I could add a setting for this.

**Comment by chochos** [comment] 2017-03-02 19:26
Closing this and opened #84 instead (a more general solution to this problem)

**Closed by chochos** 2017-03-02 19:26 UTC
